version: '3.8'
services:

  db_users:
    container_name: db_users
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_msvc_usuarios:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_users
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=example --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - spring

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    ports:
      - "8181:8080"
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev","--import-realm" ]
    volumes:
      - keycloak_reamls_data:/opt/keycloak/data/

volumes:
  mysql_msvc_usuarios:
    external: false
  keycloak_reamls_data:
    external: false

networks:
  spring: